version: '3.3'

services:
  django:
    build: .
    command: sh -c "python3 manage.py runserver"
    volumes:
      - ./chess_project:/backend
      - static_data:/backend/static_data
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://user_name:passworddb:5432/chess_project
      - DEBUG=1
  postgres:
    image: 'postgres:12.11'
    expose:
      - 5432
    environment:
      POSTGRES_USER: user_name      
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess_project

volumes:
  pg_data:
  static_data: